name: ZIP Dosyasini Otomatik Klasore Cikar

on:
  push:
    branches:
      - main  # Eger ana dalinizin adı master ise burayi master yapın
  workflow_dispatch: # Manuel tetikleme butonu ekler

jobs:
  unzip-islemi:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dosyaları klasöre yazabilmesi için şarttır

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: ZIP Dosyasini Klasorlere Ayir
        run: |
          # Depodaki .zip dosyasını bulur ve tamamen dışarı çıkarır
          unzip -o *.zip
          
          # Deponun ana sayfasında kalabalık etmesin diye orijinal ZIP'i siliyoruz
          rm *.zip

      - name: Klasorleri Depoya Geri Yukle
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Build: ZIP icerigi basariyla klasorlere cikarildi" || exit 0
          git push origin main
          
